### PR TITLE
Add inotify_exporter to the ndt-support package

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds the inotify_exporter to the NDT support package.

With this change, the inotify_exporter is built and included in the NDT RPM. When NDT starts or stops, the inotify exporter is also started or stopped.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-support/44)

### CODE REVIEW

**Comment by nkinkade** [comment]
Added a couple comments. Sorry for the delay in this review. I never received a notification from Github about this!

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[init/start.sh, line 66 at r1](https://reviewable.io:443/reviews/m-lab/ndt-support/44#-KxtJanJc63lDMPbJe_W:-KxtJanJc63lDMPbJe_X:bo4c659) ([raw file](https://github.com/m-lab/ndt-support/blob/3d80b3e7857cc7cc8b5eed040868a1502b929439/init/start.sh#L66)):*
> ```Shell
>     echo "Starting inotify_exporter:"
>     nohup $SLICEHOME/build/bin/inotify_exporter --path /var/spool/iupui_ndt &> /dev/null &
>     touch /var/lock/subsys/inotify_exporter
> ```

Could this logic, and that of `stop.sh`, be a bit more robust if you write the PID to this file? Then when starting or stopping you don't need to grep for processes but can expect a precise PID.

---

*[init/start.sh, line 67 at r1](https://reviewable.io:443/reviews/m-lab/ndt-support/44#-KxtJwpeJo5xBwWaZtU9:-KxtJwpeJo5xBwWaZtUA:b-6r90kc) ([raw file](https://github.com/m-lab/ndt-support/blob/3d80b3e7857cc7cc8b5eed040868a1502b929439/init/start.sh#L67)):*
> ```Shell
>     nohup $SLICEHOME/build/bin/inotify_exporter --path /var/spool/iupui_ndt &> /dev/null &
>     touch /var/lock/subsys/inotify_exporter
> fi
> ```

Would it be useful to write a message that `inotify_exporter` wasn't started because it was already running? It only occurs to me because it almost seems like an error condition that we should be attempting to start NDT using this script yet this particular thing is arleady running.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-support/44#-:-KxtKNM6lk1CQbIN-Bsm:b-xfe48i)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[init/start.sh, line 66 at r1](https://reviewable.io:443/reviews/m-lab/ndt-support/44#-KxtJanJc63lDMPbJe_W:-KxtQDGwg44J41jLzpDK:b-6f9295) ([raw file](https://github.com/m-lab/ndt-support/blob/3d80b3e7857cc7cc8b5eed040868a1502b929439/init/start.sh#L66)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Could this logic, and that of `stop.sh`, be a bit more robust if you write the PID to this file? Then when starting or stopping you don't need to grep for processes but can expect a precise PID.
</blockquote></details>

Okay. Let's try.

---

*[init/start.sh, line 67 at r1](https://reviewable.io:443/reviews/m-lab/ndt-support/44#-KxtJwpeJo5xBwWaZtU9:-KxtQGwKm5iD6mJsgwKl:baeqfho) ([raw file](https://github.com/m-lab/ndt-support/blob/3d80b3e7857cc7cc8b5eed040868a1502b929439/init/start.sh#L67)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Would it be useful to write a message that `inotify_exporter` wasn't started because it was already running? It only occurs to me because it almost seems like an error condition that we should be attempting to start NDT using this script yet this particular thing is arleady running.
</blockquote></details>

I've added "Already running" messages for all the above processes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-support/44)*

**Comment by stephen-soltesz** [comment]
@nkinkade PTAL?

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-support/44#-:-KxtQOh5dcmpZ3yPHNuF:b-n49g7w)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-support/44#-:-KxtR_0V4hFonv0tMX5z:bnfp4nl)*

**Pull request merged**
